ignore:
  - "src/main/java/edu/fiuba/algo3/controlador"
  - "src/main/java/edu/fiuba/algo3/vista"
  - "src/main/java/edu/fiuba/algo3/App.java"
  - "src/main/java/edu/fiuba/algo3/Main.java"
  - "src/main/java/edu/fiuba/algo3/SystemInfo.java"
  - "src/main/java/edu/fiuba/algo3/modelo/ModeloJuego.java"

coverage:
  status:
    project:
      default:
        target: 90%
    patch:
      default:
        target: 90%
