@startuml

actor Jugador
participant CambioDeVehiculo
participant Vehiculo

Jugador -> CambioDeVehiculo ++ : chocarCon(this)
CambioDeVehiculo -> Jugador ++ : getVehiculo()
return vehiculo

CambioDeVehiculo -> Vehiculo ++ : cambio()
return siguienteVehiculo

CambioDeVehiculo -> Jugador : setVehiculo(siguienteVehiculo)

@enduml
