@startuml

actor Jugador
participant Favorable

Jugador -> Favorable ++ : chocarCon(this)
Favorable -> Jugador ++ : getMovimientos()
return movimientos

Favorable -> Favorable ++ : calcularMovimientosDescontados(movimientos)
return movimientosDescontados

note right of Favorable
	movimientosActuales = movimientos - movimientosDescontados
end note

Favorable -> Jugador : setMovimientos(movimientosActuales)

@enduml
